//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGZ.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tickets
    {
        public long ID { get; set; }
        public string TicketID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
        public int Severity { get; set; }
        public int Priority { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public int Status { get; set; }
    }
}
